ecmaFeatures:
  globalReturn: true
  modules: true
env:
  browser: true
  es6: true
  node: true
globals:
  document: false
  window: false
parser: "babel-eslint"
extends:
  - eslint:recommended
  - standard

